version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"   # host_port from .env -> forward to container’s internal port
    env_file: .env        # load .env into container so process.env.PORT works
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    command: ["node", "index.js"]
