# docker-compose.yml
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    # Define shared enviroment and PLEASE anything sensitive information (ex: secret key) on the .env file
    env_file:
      - .env
